/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MahasiswaForm.java
 * 
 * Created on Oct 22, 2011, 2:56:09 PM
 */
package universitas;

import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author indra
 */
@SuppressWarnings("serial")
public class MahasiswaForm extends javax.swing.JFrame {

    DefaultTableModel mahasiswaTableModel = new ReadonlyTableModel();
    final Connection dbConnection;
    Statement sqlStatement;
    final String select_sql;
    final DateFormat dateFormater = new SimpleDateFormat("dd/MM/yyyy");
    Date savedTanggalLahir;

    /** Creates new form MahasiswaForm */
    public MahasiswaForm() {
        initComponents();
        mahasiswaTable.setModel(mahasiswaTableModel);
        mahasiswaTableModel.addColumn("nim");
        mahasiswaTableModel.addColumn("Nama");
        mahasiswaTableModel.addColumn("Tanggal Lahir");
        mahasiswaTableModel.addColumn("Jurusan");
        mahasiswaTableModel.addColumn("Alamat");

        dbConnection = KoneksiDatabase.getKoneksi();
        try {
            sqlStatement = dbConnection.createStatement();
        } catch (SQLException e) {
            System.err.println(e);
        }
        select_sql = "SELECT * FROM mahasiswa";

        loadData();

        mahasiswaTable.setModel(mahasiswaTableModel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavigasiButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nimTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jurusanTextField = new javax.swing.JTextField();
        lahirFormattedTextField = new javax.swing.JFormattedTextField();
        tambahButton = new javax.swing.JButton();
        ubahButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mahasiswaTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mahasiswaRadioButton = new javax.swing.JRadioButton();
        matakuliahRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Indra's Universitas - Mahasiswa");
        setResizable(false);

        jLabel1.setText("NIM");

        jLabel2.setText("Nama:");

        jLabel3.setText("Tanggal Lahir:");

        jLabel4.setText("Jurusan:");

        jLabel5.setText("Alamat");

        lahirFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yyyy"))));

        tambahButton.setText("Tambah");
        tambahButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahButtonMouseClicked(evt);
            }
        });

        ubahButton.setText("Ubah");
        ubahButton.setEnabled(false);
        ubahButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahButtonMouseClicked(evt);
            }
        });

        hapusButton.setText("Hapus");
        hapusButton.setEnabled(false);
        hapusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusButtonMouseClicked(evt);
            }
        });

        mahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        mahasiswaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mahasiswaTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mahasiswaTable);

        alamatTextArea.setColumns(20);
        alamatTextArea.setRows(5);
        jScrollPane2.setViewportView(alamatTextArea);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 8));
        jLabel6.setForeground(new java.awt.Color(138, 195, 16));
        jLabel6.setText("tanggal/bulan/tahun");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 8));
        jLabel7.setText("indraginanjar@gmail.com");

        jLabel8.setText("Form");

        NavigasiButtonGroup.add(mahasiswaRadioButton);
        mahasiswaRadioButton.setSelected(true);
        mahasiswaRadioButton.setText("Mahasiswa");

        NavigasiButtonGroup.add(matakuliahRadioButton);
        matakuliahRadioButton.setText("Matakuliah");
        matakuliahRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matakuliahRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)
                        .addGap(75, 75, 75)
                        .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4)
                        .addGap(59, 59, 59)
                        .addComponent(jurusanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel5)
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ubahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lahirFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(82, 82, 82)
                                .addComponent(mahasiswaRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(matakuliahRadioButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(92, 92, 92)
                                .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mahasiswaRadioButton)
                        .addComponent(matakuliahRadioButton))
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lahirFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4))
                    .addComponent(jurusanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahButton)
                    .addComponent(ubahButton)
                    .addComponent(hapusButton))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahButtonMouseClicked
        try {
            String sql = "INSERT INTO mahasiswa VALUES (?, ?, ?, ?, ?)";
            PreparedStatement p = dbConnection.prepareStatement(sql);
            p.setString(1, nimTextField.getText());
            p.setString(2, namaTextField.getText());
            p.setDate(3, new java.sql.Date(
                    ((Date) lahirFormattedTextField.getValue()).getTime()));
            p.setString(4, jurusanTextField.getText());
            p.setString(5, alamatTextArea.getText());
            p.executeUpdate();
            p.close();
        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Seluruh field mesti diisi lengkap");
        } catch (SQLException e) {
            System.err.println(e);
        }
        loadData();
        emptyAllTextField();

    }//GEN-LAST:event_tambahButtonMouseClicked

    private void ubahButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahButtonMouseClicked
        final int i = mahasiswaTable.getSelectedRow();
        if (i == -1) {
// tidak ada baris terseleksi
            return;
        }
// ambil nim yang terseleksi
        String nim = (String) mahasiswaTableModel.getValueAt(i, 0);
        String nama = namaTextField.getText();
        java.util.Date tanggalLahir = (java.util.Date) lahirFormattedTextField.getValue();
        String jurusan = jurusanTextField.getText();
        String alamat = alamatTextArea.getText();
        try {
            String sql = "UPDATE mahasiswa SET nama = ?, tanggal_lahir = ?, jurusan = ?, alamat = ? where nim = ?";
            PreparedStatement p = dbConnection.prepareStatement(sql);
            p.setString(1, nama);
            p.setDate(2, new java.sql.Date(tanggalLahir.getTime()));
            p.setString(3, jurusan);
            p.setString(4, alamat);
            p.setString(5, nim);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.err.println(e);
        }
        loadData();




    }//GEN-LAST:event_ubahButtonMouseClicked

    private void hapusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusButtonMouseClicked
        int selectedRow = mahasiswaTable.getSelectedRow();
        if (selectedRow == -1) {
// tidak ada baris terseleksi
            return;
        }
        String nim = (String) mahasiswaTableModel.getValueAt(selectedRow, 0);
        try {
            String sql = "DELETE FROM mahasiswa WHERE NIM = ?";
            PreparedStatement p = dbConnection.prepareStatement(sql);
            p.setString(1, nim);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.err.println(e);
        }
        loadData();
        emptyAllTextField();

    }//GEN-LAST:event_hapusButtonMouseClicked

    private void mahasiswaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mahasiswaTableMouseClicked
        int selectedRow = mahasiswaTable.getSelectedRow();
        // jika tak ada baris terseleksi
        if (selectedRow == -1) {
            emptyAllTextField();
            ubahButton.setEnabled(false);
            hapusButton.setEnabled(false);
            return;
        }
        ubahButton.setEnabled(true);
        hapusButton.setEnabled(true);
        String nim = (String) mahasiswaTableModel.getValueAt(selectedRow, 0);
        nimTextField.setText(nim);
        String nama = (String) mahasiswaTableModel.getValueAt(selectedRow, 1);
        namaTextField.setText(nama);
        java.util.Date tanggalLahir = (java.util.Date) mahasiswaTableModel.getValueAt(selectedRow, 2);
        lahirFormattedTextField.setValue(tanggalLahir);
        String jurusan = (String) mahasiswaTableModel.getValueAt(selectedRow, 3);
        jurusanTextField.setText(jurusan);
        String alamat = (String) mahasiswaTableModel.getValueAt(selectedRow, 4);
        alamatTextArea.setText(alamat);

    }//GEN-LAST:event_mahasiswaTableMouseClicked

    private void matakuliahRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matakuliahRadioButtonActionPerformed
        NavigationUtil.showMatakuliahForm();
        mahasiswaRadioButton.setSelected(true);
    }//GEN-LAST:event_matakuliahRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MahasiswaForm().setVisible(true);
            }
        });
    }

    private void loadData() {
// menghapus seluruh data
        mahasiswaTableModel.getDataVector().removeAllElements();
// memberi tahu bahwa data telah kosong
        mahasiswaTableModel.fireTableDataChanged();
        try {

            ResultSet r = sqlStatement.executeQuery(select_sql);
            while (r.next()) {
// lakukan penelusuran baris
                Object[] newRowFields = new Object[5];
                newRowFields[0] = r.getString("nim");
                newRowFields[1] = r.getString("nama");
                savedTanggalLahir = r.getDate("tanggal_lahir");
                newRowFields[2] = savedTanggalLahir;
                newRowFields[3] = r.getString("jurusan");
                newRowFields[4] = r.getString("alamat");
                mahasiswaTableModel.addRow(newRowFields);
            }
            r.close();
            mahasiswaTable.getColumnModel().getColumn(2).setCellRenderer(new TableCellRenderer() {

                @Override
                public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                    table.getEditorComponent();
                    JLabel valueLabel = null;
                    valueLabel = new JLabel(dateFormater.format(value));
                    valueLabel.setFont(table.getFont());
                    JTextField renderer = new JTextField(dateFormater.format(value));
                    renderer.setBorder(null);
                    renderer.setBorder(table.getBorder());
                    if(isSelected){
                        renderer.setBackground(table.getSelectionBackground());
                        if(hasFocus){
                            renderer.setBorder(BorderFactory.createLineBorder(new Color(table.getGridColor().getRGB())));
                        }
                    }
                    else{
                        renderer.setBackground(table.getBackground());
                    }
                    return renderer;
                }
            });
        } catch (SQLException e) {
            System.err.println(e);
        }
    }

    void emptyAllTextField() {
        nimTextField.setText(null);
        namaTextField.setText(null);
        lahirFormattedTextField.setText(null);
        jurusanTextField.setText(null);
        alamatTextArea.setText(null);
        ubahButton.setEnabled(false);
        hapusButton.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup NavigasiButtonGroup;
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jurusanTextField;
    private javax.swing.JFormattedTextField lahirFormattedTextField;
    private javax.swing.JRadioButton mahasiswaRadioButton;
    private javax.swing.JTable mahasiswaTable;
    private javax.swing.JRadioButton matakuliahRadioButton;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JButton tambahButton;
    private javax.swing.JButton ubahButton;
    // End of variables declaration//GEN-END:variables
}
