/*
 * MahasiswaForm.java
 * 
 * Created on Oct 22, 2011, 2:56:09 PM
 */
package universitas;

import com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author indraginanjar@gmail.com
 */
@SuppressWarnings("serial")
public class MatakuliahForm extends javax.swing.JFrame {

    ReadonlyTableModel tableModel = new ReadonlyTableModel();
    final Connection dbConnection;
    Statement sqlStatement;
    String selectedKode;
    final String selectSql;
    int selectedRow;

    /** Creates new form MahasiswaForm */
    public MatakuliahForm() {
        initComponents();
        table.setModel(tableModel);
        tableModel.addColumn("Kode");
        tableModel.addColumn("Nama");
        tableModel.addColumn("SKS");
        tableModel.addColumn("Semester");

        dbConnection = DatabaseUtil.getConnection();
        try {
            sqlStatement = dbConnection.createStatement();
        } catch (SQLException e) {
            System.err.println(e);
        }
        selectSql = "SELECT * FROM matakuliah";

        loadData();

        table.setModel(tableModel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavigationButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        kodeTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tambahButton = new javax.swing.JButton();
        ubahButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        semesterFormattedTextField = new javax.swing.JFormattedTextField();
        sksFormatedTextField = new javax.swing.JFormattedTextField();
        mahasiswaRadioButton = new javax.swing.JRadioButton();
        matakuliahRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Indra's Universitas - Matakuliah");
        setMinimumSize(new java.awt.Dimension(534, 604));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Kode:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 54, -1, 20));
        getContentPane().add(kodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 54, 330, -1));

        jLabel2.setText("Nama:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 94, -1, -1));
        getContentPane().add(namaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 94, 330, -1));

        jLabel4.setText("SKS:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 139, -1, 10));

        jLabel5.setText("Semester:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        tambahButton.setText("Tambah");
        tambahButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahButtonMouseClicked(evt);
            }
        });
        getContentPane().add(tambahButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 100, -1));

        ubahButton.setText("Ubah");
        ubahButton.setEnabled(false);
        ubahButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ubahButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 340, 110, -1));

        hapusButton.setText("Hapus");
        hapusButton.setEnabled(false);
        hapusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusButtonMouseClicked(evt);
            }
        });
        getContentPane().add(hapusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 340, 100, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 392, 470, 182));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel7.setText("indraginanjar@gmail.com");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 574, -1, -1));

        semesterFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(semesterFormattedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 30, -1));

        sksFormatedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(sksFormatedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 139, 30, -1));

        NavigationButtonGroup.add(mahasiswaRadioButton);
        mahasiswaRadioButton.setText("Mahasiswa");
        mahasiswaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mahasiswaRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mahasiswaRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 12, -1, -1));

        NavigationButtonGroup.add(matakuliahRadioButton);
        matakuliahRadioButton.setSelected(true);
        matakuliahRadioButton.setText("Matakuliah");
        getContentPane().add(matakuliahRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 12, -1, -1));

        jLabel3.setText("Form:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 16, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahButtonMouseClicked
        if(ubahButton.isEnabled()){
            emptyAllTextField();
            return;
        }
        if(!InputUtil.isAllTextComponentFilled(this, 
                "Seluruh field mesti diisi lengkap")){
            return;
        }        
        try {
            String sql = "INSERT INTO matakuliah VALUES (?, ?, ?, ?)";
            PreparedStatement p = dbConnection.prepareStatement(sql);
            p.setString(1, kodeTextField.getText());
            p.setString(2, namaTextField.getText());
            p.setString(3, sksFormatedTextField.getText());
            p.setString(4, semesterFormattedTextField.getText());
            p.executeUpdate();
            p.close();
        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Seluruh field mesti diisi lengkap");
        } catch (MySQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(this, "Kode yang dimasukkan, sudah ada");
        } catch (SQLException e) {
            System.err.println(e);
        }
        loadData();
        emptyAllTextField();

    }//GEN-LAST:event_tambahButtonMouseClicked

    private void ubahButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahButtonMouseClicked
        if (selectedKode == null) {
            // tidak ada baris terseleksi
            return;
        }
        // ambil kode yang terseleksi
        try {
            String sql = "UPDATE matakuliah SET nama_mtk = ?, sks = ?, semester = ? where kode_mtk = ?";
            PreparedStatement p = dbConnection.prepareStatement(sql);
            p.setString(1, namaTextField.getText());
            p.setString(2, sksFormatedTextField.getText());
            p.setString(3, semesterFormattedTextField.getText());
            p.setString(4, selectedKode);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.err.println(e);
        }
        loadData();
        table.getSelectionModel().setSelectionInterval(selectedRow, selectedRow);



    }//GEN-LAST:event_ubahButtonMouseClicked

    private void hapusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusButtonMouseClicked
        if (selectedKode == null) {
            // tidak ada baris terseleksi
            return;
        }
        try {
            String sql = "DELETE FROM matakuliah WHERE kode_mtk = ?";
            PreparedStatement p = dbConnection.prepareStatement(sql);
            p.setString(1, selectedKode);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.err.println(e);
        }
        loadData();
        emptyAllTextField();

    }//GEN-LAST:event_hapusButtonMouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        selectedRow = table.getSelectedRow();
        // jika tak ada baris terseleksi
        if (selectedRow == -1) {
            emptyAllTextField();
            selectedKode = null;
            ubahButton.setEnabled(false);
            hapusButton.setEnabled(false);
            return;
        }
        ubahButton.setEnabled(true);
        hapusButton.setEnabled(true);
        selectedKode = (String) tableModel.getValueAt(selectedRow, 0);
        kodeTextField.setText(selectedKode);
        namaTextField.setText((String) tableModel.getValueAt(selectedRow, 1));
        sksFormatedTextField.setText((String) tableModel.getValueAt(selectedRow, 2));
        semesterFormattedTextField.setText((String) tableModel.getValueAt(selectedRow, 3));
    }//GEN-LAST:event_tableMouseClicked

    private void mahasiswaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mahasiswaRadioButtonActionPerformed
        NavigationUtil.showMahasiswaForm();
        matakuliahRadioButton.setSelected(true);
    }//GEN-LAST:event_mahasiswaRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MatakuliahForm().setVisible(true);
            }
        });
    }

    private void loadData() {
        try {
            ResultSet rs = sqlStatement.executeQuery(selectSql);
            tableModel.readResultSet(rs);
            rs.close();
        } catch (SQLException e) {
            System.err.println(e);
        }
    }

    void emptyAllTextField() {
        InputUtil.emptyAllTextComponent(this);
        ubahButton.setEnabled(false);
        hapusButton.setEnabled(false);
        if(selectedRow != -1){
            table.removeRowSelectionInterval(selectedRow, selectedRow);
        }
        selectedRow = -1;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup NavigationButtonGroup;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kodeTextField;
    private javax.swing.JRadioButton mahasiswaRadioButton;
    private javax.swing.JRadioButton matakuliahRadioButton;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JFormattedTextField semesterFormattedTextField;
    private javax.swing.JFormattedTextField sksFormatedTextField;
    private javax.swing.JTable table;
    private javax.swing.JButton tambahButton;
    private javax.swing.JButton ubahButton;
    // End of variables declaration//GEN-END:variables
}
